In [7]:
import crypten 
import torch
crypten.init()

In [8]:
# Create torch tensor
x = torch.tensor([1.0, 2.0, 3.0])

# Encrypt x
x_enc = crypten.cryptensor(x)

# Decrypt x
x_dec = x_enc.get_plain_text()   
crypten.print(x_dec)


# Create python list
y = [4.0, 5.0, 6.0]

# Encrypt x
y_enc = crypten.cryptensor(y)

# Decrypt x
y_dec = y_enc.get_plain_text()
crypten.print(y_dec)

tensor([1., 2., 3.])
tensor([4., 5., 6.])


In [9]:
z_enc=x_enc*y_enc

In [10]:
print(z_enc)

MPCTensor(
	_tensor=tensor([ 262144,  655360, 1179648])
	plain_text=HIDDEN
	ptype=ptype.arithmetic
)


In [11]:
print(z_enc.get_plain_text())

tensor([ 4., 10., 18.])
